apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
