# deploy/eks/k8s-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 423735920800.dkr.ecr.us-east-1.amazonaws.com/my-auth-service:latest
        ports:
        - containerPort: 3001
